
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 32;
  public static final int MENOSMENOS = 33;
  public static final int POR = 6;
  public static final int GE = 25;
  public static final int ENTERO = 12;
  public static final int INT = 30;
  public static final int FOR = 16;
  public static final int MINUS = 19;
  public static final int CP = 9;
  public static final int NOT = 21;
  public static final int AND = 22;
  public static final int IGUAL = 20;
  public static final int LT = 26;
  public static final int OR = 23;
  public static final int DIV = 7;
  public static final int IF = 14;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int MENOS = 5;
  public static final int MOD = 34;
  public static final int IDENT = 13;
  public static final int EQ = 29;
  public static final int CLL = 11;
  public static final int ELSE = 15;
  public static final int TO = 35;
  public static final int WHILE = 2;
  public static final int NE = 28;
  public static final int ALL = 10;
  public static final int DOWNTO = 36;
  public static final int AP = 8;
  public static final int GT = 24;
  public static final int PRINT = 17;
  public static final int DO = 3;
  public static final int STEP = 37;
  public static final int PYC = 18;
  public static final int MAS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "DO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "ENTERO",
  "IDENT",
  "IF",
  "ELSE",
  "FOR",
  "PRINT",
  "PYC",
  "MINUS",
  "IGUAL",
  "NOT",
  "AND",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "NE",
  "EQ",
  "INT",
  "COMA",
  "MASMAS",
  "MENOSMENOS",
  "MOD",
  "TO",
  "DOWNTO",
  "STEP"
  };
}

